### ISSUE TITLE
Numerical references or path values result in “mismatched input” error

### ISSUE THREAD

**Issue by dnicolson** [Serchinastico/Kin#109]
The following will produce the error:
```
path = 0840;
```

References that contain only numbers also have the same issue.

**Comment by drekka** [comment]
Same here. Finding this on custom settings containing hex API keys

**Comment by Serchinastico** [comment]
Hi!

Somehow the issue slipped through the cracks so apologies. Anyways, I sent a PR to fix it and should be available in the next version of Kin in a few hours.

Thanks for the report (and the reminder!) 🙌
