### ISSUE TITLE
Error with new Xcode16 PBXFileSystemSynchronizedRootGroup 

### ISSUE THREAD

**Issue by timath98** [Serchinastico/Kin#117]
Hello 
We have created a new Group using Xcode 16 in our project, and this seems to be causing problems.

Here's the error report:
`ERROR: line 446:9 no viable alternative at input 'EBBEDCFF2CE657960005B6D4 {isa=PBXFileSystemSynchronizedBuildFileExceptionSet'`

And here's what the .pbxproj looks like:

```
/* Begin PBXFileSystemSynchronizedBuildFileExceptionSet section */
		EBBEDCFF2CE657960005B6D4 /* PBXFileSystemSynchronizedBuildFileExceptionSet */ = {
			isa = PBXFileSystemSynchronizedBuildFileExceptionSet;
			membershipExceptions = (
				Info.plist,
			);
			target = EBBEDCEB2CE657940005B6D4 /* Widget */;
		};
/* End PBXFileSystemSynchronizedBuildFileExceptionSet section */

/* Begin PBXFileSystemSynchronizedRootGroup section */
		EBBEDCF12CE657940005B6D4 /* Widget */ = {isa = PBXFileSystemSynchronizedRootGroup; exceptions = (EBBEDCFF2CE657960005B6D4 /* PBXFileSystemSynchronizedBuildFileExceptionSet */, ); explicitFileTypes = {}; explicitFolders = (); path = Widget; sourceTree = "<group>"; };
/* End PBXFileSystemSynchronizedRootGroup section */
```

**Comment by Serchinastico** [comment]
Hi @timath98 ! I will take a look to the issue next week but feel free to send a PR if you feel like it and I will personally review it 😄

**Comment by Serchinastico** [comment]
Version [2.1.11](https://github.com/Serchinastico/Kin/releases/tag/2.1.11) should fix this. Let me know if you find any other issue!
