### ISSUE TITLE
LastSwift Migration Warning is not correct anymore

### ISSUE THREAD

**Issue by davideme** [Serchinastico/Kin#31]
The following error is now invalid as `ProvisioningStyle = Automatic;` can be the last param.
ERROR: line 1320:6 mismatched input 'LastSwiftMigration' expecting '}'
```
A1F9D0091F5951EE0078CB66 = {
						CreatedOnToolsVersion = 8.3.3;
						DevelopmentTeam = CWB42KSFAW;
						LastSwiftMigration = 0900;
						ProvisioningStyle = Automatic;
					};
```

**Comment by dnicolson** [comment]
I think this is a duplicate of https://github.com/Karumi/Kin/issues/22 which has been fixed.

**Comment by Serchinastico** [comment]
Confirmed, it has been already fixed 👍🏼
