### ISSUE TITLE
Pip does not support python 2 anymore

### ISSUE THREAD

**Issue by maciejkarolczyk** [Serchinastico/Kin#67]
Hello I have a problem,

I've installed Kin using the most recent Pip (python3) and when tried to use it I get an error:

`Traceback (most recent call last):
  File "/usr/local/bin/kin", line 5, in <module>
    from kin.kin import main
  File "/usr/local/lib/python3.9/site-packages/kin/kin.py", line 5, in <module>
    from verifier import Verifier
ModuleNotFoundError: No module named 'verifier'`

I've read on the forum that Kin is made for python 2.7 only. Is it true? If so, is Kin unusable now since Pip supports only python 3 now?

**Comment by Serchinastico** [comment]
Hi @maciejkarolczyk !

Yeah, originally Kin was created with Python 2.7 and we just recently updated it to work with Python 3 [here](https://github.com/Karumi/Kin/pull/65) (Big kudos to @dnicolson 🙌). However, we didn't release this updated version yet, but will do very soon and will let you know in this issue when that happens 😄.

**Comment by Serchinastico** [comment]
Sorry for the delay, Kin is now built with Python 3 so we can close the issue 😄
