### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ahmedfaaid** [Serchinastico/Kin#77]
Hi,

I tried to run kin for the first time and I keep getting this error. I am not sure why.

```
Traceback (most recent call last):
  File "/usr/local/bin/kin", line 5, in <module>
    from kin.kin import main
  File "/usr/local/lib/python2.7/site-packages/kin/kin.py", line 5, in <module>
    from .verifier import Verifier
  File "/usr/local/lib/python2.7/site-packages/kin/verifier.py", line 2, in <module>
    from .grammar.PBXProjLexer import PBXProjLexer
  File "/usr/local/lib/python2.7/site-packages/kin/grammar/PBXProjLexer.py", line 1165
    def __init__(self, input=None, output:TextIO = sys.stdout):
                                         ^
SyntaxError: invalid syntax
```

**Comment by davideme** [comment]
Are you trying to run a Python 3 project with Python 2?

**Comment by ahmedfaaid** [comment]
I have both Python 3 and 2 installed but kin doesn't support that correct?

**Comment by dnicolson** [comment]
I see a similar error with Python 3 and Kin 1.7.4.

If you uninstall Kin and run `pip3 install kin` it should install Kin 2.0.2 and work with Python 3.

**Comment by Serchinastico** [comment]
Since version 2.0.0 Kin is now Python3 only so you should run `pip3 install kin` as @dnicolson said
