### ISSUE TITLE
Improve Usage Instructions

### ISSUE THREAD

**Issue by korhancgebologlu** [Serchinastico/Kin#84]
I downloaded kin but cannot run on project. I donot believe it just me couldn't follow the instructions.
In Usage section,
it mentions download with pip but pip is not available on new MacBooks. if Pip3 is the option then cool But the next step is less instructive than the download section.
After downloading, run kin it states however packages installed from pip can not be directly called from command line.
That's why, I started with python3 command to open an interpreter. It didn't work with directly calling kin or importing kin.
Couple re-try and re-start weren't helpful as well. Then, I searched for a better guide. Not a chance of course. 
The only useful resource was this [medium article](https://medium.com/@soxjke/kin-medicine-for-headache-with-pbxproj-merge-e0562b76519f). After that, I tried to kin to command line. I found [this](https://packaging.python.org/en/latest/guides/installing-stand-alone-command-line-tools/). Usage of pipx helped me to get there. 
After following the instructions for pipx download. I finally was able to use kin in my computer. 
This process shouldnot be this hard. This can be updated so quickly and the next person should not have spend as much time as I spent.
So, How is this usage instructions improved? and How can I help?

**Comment by Serchinastico** [comment]
Hi @korhancgebologlu! Thanks for your input, I really appreciate it.

> After following the instructions for pipx download. I finally was able to use kin in my computer.
This process shouldnot be this hard. This can be updated so quickly and the next person should not have spend as much time as I spent.

Fair point, I don't usually code in Python so I'm out of tune here but I believe pip3/pipx should be the to-go option here, I'll update the docs to make it clear that pipx is the preferred way to use kin.

**Comment by Serchinastico** [comment]
Hope this helps to future users of Kin: https://github.com/Serchinastico/Kin/commit/f69d0dc4bff1405ad948a6c408e2a0e58ea39bab

**Comment by korhancgebologlu** [comment]
hi @Serchinastico,
thanks for your quick response and quick fix for this. 
I really appreciate the power of this tool.
