### ISSUE TITLE
Kin not found in mac os

### ISSUE THREAD

**Issue by simoghrissi** [Serchinastico/Kin#85]
Hello, 
I tried to run kin after pip3 install but i always have the error :  kin: command not found

**Comment by Serchinastico** [comment]
Hi @simoghrissi 

I'm happy to help! It can be a number of things so let's try to find out what's going on. 

- Have you ever run any other command you installed with pip3 before or is Kin the first one? 
- Can you run `pip3 show kin` for me? What's the value of the `Location` field?

Without further information, I think what's probably happening is that `pip3` executables are not part of your `$PATH` so your shell doesn't find `kin` anywhere, even if it's installed properly. Try following the instructions I found on the internet: https://www.kisphp.com/os-x/find-pip-package-executable-on-mac.

Cheers.

**Comment by simoghrissi** [comment]
Hello thank you for the answer : 
No kin is the first command i run with pip3 

pip show kin : 
Name: kin
Version: 2.1.0
Summary: A simple project.pbxproj verifier
Home-page: https://github.com/Karumi/Kin
Author: Karumi
Author-email: tech@karumi.com
License: Apache Software
Location: /Users/mt5619/Library/Python/3.9/lib/python/site-packages
Requires: antlr4-python3-runtime, argparse
Required-by:

**Comment by Serchinastico** [comment]
It looks like your Python version is the one running by default in Mac and your `PATH` is probably not referencing new packages installed there. Two options here:

- Either you find where are the scripts are installed in your current Python installation and update your PATH to point there: https://stackoverflow.com/a/62151306
- Or you install a new Python version using something like Homebrew that takes care of these things for you: https://docs.brew.sh/Homebrew-and-Python

**Comment by simoghrissi** [comment]
Yes finaly work 
[https://stackoverflow.com/a/62151306](url) resolve the issue ;) 
Thank you for your help and your great work ;)

**Comment by Serchinastico** [comment]
Fantastic news!
