### ISSUE TITLE
mismatched input '1' expecting NON_QUOTED_STRING

### ISSUE THREAD

**Issue by ezoushen** [Serchinastico/Kin#86]
Hi,

I noticed that the warning on the BuildIndependentTargetsInParallel field, located under `Begin PBXProject section`/`Project object`/attributes, is triggering falsely. Despite being set to 1, my project is working correctly and the error message is unnecessary. Please let me know if you require additional information regarding this issue.

### Environment: 

Xcode 14.2 on Ventura 13.2.1

### Part of my `.pbxproj` file:
```
/* Begin PBXProject section */
		151C376429A313FA00528ECF /* Project object */ = {
			isa = PBXProject;
			attributes = {
				BuildIndependentTargetsInParallel = 1;
```

**Comment by Serchinastico** [comment]
Hi @ezoushen!

Thanks for the report, I'll see if I can reproduce it myself and fix it for the next version, I will let you know if I find any blocker in the way.

**Comment by Serchinastico** [comment]
@ezoushen [2.1.1](https://github.com/Serchinastico/Kin/releases/tag/2.1.1) contains a fix for this and should be already published and available in pypy, I hope that helps!

https://github.com/Serchinastico/Kin/actions/runs/4574074279

**Comment by ezoushen** [comment]
@Serchinastico Upgraded and tested. Great job, thank you!
