### ISSUE TITLE
Error with Xcode Build Tool Plug-in

### ISSUE THREAD

**Issue by mfamilar** [Serchinastico/Kin#90]
We're using an Xcode Build Tool Plug-in in our project, and this seems to be causing problems.

Here's the error report:
`ERROR: line 979:3 mismatched input 'productRef' expecting {'platformFilter', 'platformFilters', 'name', 'target', 'targetProxy'}`

And here's what the `.pbxproj` looks like:
```
F5F962002AD03AE000D334DA /* PBXTargetDependency */ = {
	isa = PBXTargetDependency;
	productRef = F5F961FF2AD03AE000D334DA /* SwiftlintPlugin */;
};
```

**Comment by Serchinastico** [comment]
Hi @mfamilar ,

I'll take a look this week and report you back once it's fixed 😄

**Comment by mfamilar** [comment]
Hi @Serchinastico,

Thank you for your reply, and sorry for the delay.

I just tried it again, and unfortunately it seems that the problem is still present.
I tried with version [2.1.4](https://github.com/Serchinastico/Kin/releases/tag/2.1.4)

Here is the error message (which is different from the first time): 
`ERROR: line 1014:2 mismatched input '}' expecting {'target', 'targetProxy'}`

The `.pbxproj` has not changed from my last message.

**Comment by Serchinastico** [comment]
Hi again @mfamilar!

It looks like the error is a different one though (it's looking for a mandatory `targetProxy` entry when there is none). I just merged a branch fixing it (by making the field optional) and that should fix it.

Version [2.1.5](https://github.com/Serchinastico/Kin/releases/tag/2.1.5) is being released right, now. Can you test with it and see if the error persists? 

Thanks!

**Comment by mfamilar** [comment]
Hi @Serchinastico,

I've just tried version [2.1.5](https://github.com/Serchinastico/Kin/releases/tag/2.1.5), and it now works ! 👍

Thank you for your swiftness and efficiency.
