### ISSUE TITLE
Add kin to homebrew

### ISSUE THREAD

**Issue by aiKrice** [Serchinastico/Kin#95]
It would be nice to install it with bundle install / bundle

**Comment by Serchinastico** [comment]
Hi @aiKrice ! That'd be awesome indeed. I don't think I have the capacity right now, but I will keep this issue high in the priority list as I'm truly interested in the process of publishing new packages in brew. As always, any help/PR working on this direction is more than welcome.

Thanks for your report!

**Comment by dnicolson** [comment]
https://github.com/Homebrew/homebrew-core/pull/161230

**Comment by dnicolson** [comment]
@Serchinastico I accidentally committed 4ca9624 to the `main` branch, can you please make a new release?

On Python version 3.12, `setuptools` is not available by default in virtual environments. We can then remove this line:
https://github.com/Homebrew/homebrew-core/pull/161230/files#diff-1f11a0f1ab2255a89968790b99e6fef5763a5a43e27bf9ec5f0afd4b52194490R11

**Comment by Serchinastico** [comment]
> @Serchinastico I accidentally committed [4ca9624](https://github.com/Serchinastico/Kin/commit/4ca96241994809ea7f3e975c5c88f36fbe9cd8e5) to the `main` branch, can you please make a new release?
> 
> On Python version 3.12, `setuptools` is not available by default in virtual environments. We can then remove this line: https://github.com/Homebrew/homebrew-core/pull/161230/files#diff-1f11a0f1ab2255a89968790b99e6fef5763a5a43e27bf9ec5f0afd4b52194490R11

I did all the steps to release [2.1.6](https://github.com/Serchinastico/Kin/releases/tag/2.1.6) but I'm having problems uploading the package to pypi (because they no longer accept user/password credentials to upload new packages). Let me see if I find a way to get the credentials back again and will report back. If you don't need the pypi package then you should be good to go.

BTW, thanks so much for your help with this issue 🙌

**Comment by dnicolson** [comment]
Thanks! There is no rush, it makes more sense to keep the current Homebrew PR as is for now.

**Comment by Serchinastico** [comment]
Cool, I managed to get the credentials, updated the offending workflow and released [2.1.6 in pypi](https://pypi.org/project/kin/) in case that helps.

**Comment by dnicolson** [comment]
It's now available in Homebrew:
```
brew update
brew install kin
```

**Comment by Serchinastico** [comment]
Thanks @dnicolson 🙌
